#!/bin/bash
# 
# Autor: Christian Daniel Avila Sánchez
# June 22th 2014
# Upload a json file to database test
# Arg[1] = json file to load to dabase
#

log="InsertLog"
date > $log

echo "Create Data base"
curl -X PUT http://127.0.0.1:5984/meteorite

echo "Reading file... " $1

echo "Inserting data..."
while read line           
do
    echo $line > temp
    curl -X POST http://127.0.0.1:5984/meteorite -d @temp -H "Content-Type: application/json" >> $log
done < $1

echo "Inserting data completed"

date >> $log
